Ordering it

diff --git a/build b/build
--- a/build
+++ b/build
@@ -6,15 +6,25 @@ this=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
 exit_fuc() 
 {
   if type "sudo" > /dev/null 2>&1 ; then
-    this_check=$(sudo docker-compose ps web-$this 2> /dev/null | tail -1) 
+    this_check=$(docker-compose ps web-$this 2> /dev/null | tail -1) 
     if [[ $this_check == *"web-$this"* ]]; then
-      sudo docker-compose rm -f web-$this
+      docker-compose rm -f web-$this
     fi
-    sudo rm -rf /tmp/gh-pages-$this 
-    sudo rm -f docker-compose-$this.yml 
+    rm -rf /tmp/gh-pages-$this 
+    rm -f docker-compose-$this.yml 
   fi
 }
 trap exit_fuc 0
+
+docker_check()
+{
+  docker_id=$(docker info 2> /dev/null | grep ^ID:)
+  if [ -z $docker_id ]; then
+    echo "Unable to connect to docker ..."
+    echo "       May be need to use sudo ..."
+    exit 1
+  fi
+}
 
 docker_gen_file()
 { 
@@ -31,9 +41,18 @@ EOL
 docker_run() 
 {
   mkdir /tmp/gh-pages-$this
-  sudo docker pull unws/gh-pages:$tag
+  docker pull unws/gh-pages:$tag
   cat docker-compose-$this.yml
-  sudo docker-compose -f docker-compose-$this.yml run web-$this -s $gitsrc -p $port
+  docker-compose -f docker-compose-$this.yml run web-$this -s $gitsrc -p $port
+}
+
+get_ip()
+{
+  if type "ifconfig" > /dev/null 2>&1 ; then
+    webip=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
+  else
+    webip="0.0.0.0"
+  fi
 }
 
 jekyll_run()
@@ -55,6 +74,9 @@ jekyll_run()
 }
 
 usage() { echo "$0 usage:" && grep " .)\ #" $0; exit 0; }
+
+### MAIN ###
+docker_check
 post_limit=0
 build_run=0
 tag="latest"
@@ -103,11 +125,7 @@ else
   git submodule update --init --recursive
 fi
 
-if type "ifconfig" > /dev/null 2>&1 ; then
-  webip=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
-else
-  webip="0.0.0.0"
-fi
+get_ip
 
 echo "-- Open http://$webip:$port/ --"
 jekyll_run > /dev/null 
